application: YOUR_APP_ID_HERE
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /oauth2callback
  script: oauth2client/appengine.py

- url: .*
  script: main.py
