application: REPLACE_ME
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /static
  static_dir: static
- url: /.*
  script: main.application
